version: "2"
services:

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbtest
    volumes:
      - ./docker/pgadmin/shared:/shared
    ports:
      - 5432:5432
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@vincenzocarlino.it
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./docker/pgadmin/shared/:/shared
    depends_on:
      - postgres
    ports:
      - 5050:80
    networks:
      - default

networks:
  default:
    driver: bridge
